version: "3.8"

services:
  backend:
    build:
      context: ./nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    cap_add:
      - NET_BIND_SERVICE

